[package]
name = "tangerine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
brotopuf = "0.1.0"
bytes = "1.11.0"
clap = { version = "4.5.53", features = ["derive"] }
fjall = "2.11.2"
ordered-float = "5.1.0"
priority-queue = "2.7.0"
thiserror = "2.0.17"
